// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/:board/:threadID": {
            "get": {
                "description": "Get thread and replies in specified board with corresponding ID.",
                "summary": "get thread contents",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/:board/:threadID/delete-thread": {
            "delete": {
                "description": "Given the ID and board of a thread, attempt to delete a thread. May be accepted or denied depending on admin's configuration.",
                "summary": "Delete thread with ID in board",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/:board/:threadID/reply": {
            "post": {
                "summary": "reply to a thread",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/:board/:threadID/replyID/delete-reply": {
            "delete": {
                "description": "Given the ID and board of a thread, as well as the ID of a reply, attempt to delete a reply. May be accepted or denied depending on admin's configuration.",
                "summary": "Delete reply with ID in thread with ID in board",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/:board/get-threads": {
            "get": {
                "description": "Gets the IDs of active threads in a board, depending on configuration of what constitutes an \"active thread\".",
                "summary": "get IDs of active threads",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/:board/new-thread": {
            "post": {
                "description": "Create a new thread in a board for others to reply to.",
                "summary": "post a new thread",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "nodeguy",
	Description:      "Backend API for a forum website.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
