basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Backend API for a forum website.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: nodeguy
  version: "0.1"
paths:
  /:board/:threadID:
    get:
      description: Get thread and replies in specified board with corresponding ID.
      responses:
        "200":
          description: OK
      summary: get thread contents
  /:board/:threadID/delete-thread:
    delete:
      description: Given the ID and board of a thread, attempt to delete a thread.
        May be accepted or denied depending on admin's configuration.
      responses:
        "200":
          description: OK
      summary: Delete thread with ID in board
  /:board/:threadID/edit-thread:
    put:
      description: Given the ID and board of a thread, attempt to edit a thread. May
        be accepted or denied depending on admin's configuration.
      responses:
        "200":
          description: OK
      summary: Edit thread with ID in board
  /:board/:threadID/reply:
    post:
      responses:
        "200":
          description: OK
      summary: reply to a thread
  /:board/:threadID/replyID/delete-reply:
    delete:
      description: Given the ID and board of a thread, as well as the ID of a reply,
        attempt to delete a reply. May be accepted or denied depending on admin's
        configuration.
      responses:
        "200":
          description: OK
      summary: Delete reply with ID in thread with ID in board
  /:board/:threadID/replyID/edit-reply:
    put:
      description: Given the ID and board of a thread, as well as the ID of a reply,
        attempt to edit a reply. May be accepted or denied depending on admin's configuration.
      responses:
        "200":
          description: OK
      summary: Edit reply with ID in thread with ID in board
  /:board/get-threads:
    get:
      description: Gets the IDs of active threads in a board, depending on configuration
        of what constitutes an "active thread".
      responses:
        "200":
          description: OK
      summary: get IDs of active threads
  /:board/new-thread:
    post:
      description: Create a new thread in a board for others to reply to.
      responses:
        "200":
          description: OK
      summary: post a new thread
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
